# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-08-18 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requests_per_day',
            field=models.IntegerField(default=0, verbose_name='requests_per_day'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='requests_per_month',
            field=models.IntegerField(default=0, verbose_name='requests_per_month'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='requests_per_week',
            field=models.IntegerField(default=0, verbose_name='requests_per_week'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='requests_total',
            field=models.IntegerField(default=0, verbose_name='requests_total'),
        ),
    ]
